spring:
  application:

  name: collect-CVs-from-google-drive
  datasource:
    url: jdbc:postgresql://localhost:5432/ais
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: dev
    change-log: /liquibase/master.xml

jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 600000
google:
  drive:
    folder:
      id: 1dWy-uqSYxJ2QelrDox_6oAAOHhxocdbT
  cloud:
    credentials:
      path: C:\\credentials\\credentials.json

minio:
  bucketName: ais
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin

